spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=labo202628
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.profiles.active=redundancy
# spring.profiles.active=undersampling